- hosts: frontends
  gather_facts: false
  tags:
    - aws.smoke
  
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: http://frontend1.{{ GUID }}.example.opentlc.com
    register: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - aws.smoke 
