- hosts: frontends
  gather_facts: false
  tags:
    - aws.smoke
  
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: http://frontend1.{{ GUID }}.example.opentlc.com
      return_content: yes
    register: webpage
    failed_when: "'Ansible has done its job' not in webpage.content"
    tags:
      - aws.smoke

